default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432

development:
  <<: *default
  database: da7t95snjt6gi7
  username: ewmnpglmzizfys
  password: WoEhKstoFoWVj5q3cFuHJTEG8K
  host: ec2-54-163-228-188.compute-1.amazonaws.com

production:
  <<: *default
  database: entherm_production
  username: postgres
  password: 12345678
  host: localhost

test:
  <<: *default
  database: entherm_test
  username: postgres
  password: 123456789
  host: localhost